name: dataflows_assessment
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0-75.1.beta


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8

  # System/Structure
  go_router: ^14.2.3
  provider: ^6.1.2
  flutter_staggered_grid_view: ^0.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/


flutter_intl:
  enabled: true